import { Activity, MessageCircle, Tags, UsersRound } from "lucide-react";
import Link from "next/link";
import { Shell } from "@/components/shell";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

export default async function StatsPage(){
  const user=await requireUser();const now=new Date();const monthAgo=new Date(now.getTime()-30*86_400_000);const previousMonth=new Date(now.getTime()-60*86_400_000);
  const [contacts,recent,previous,tags,types]=await Promise.all([db.contact.count({where:{userId:user.id}}),db.interaction.count({where:{contact:{userId:user.id},happenedAt:{gte:monthAgo}}}),db.interaction.count({where:{contact:{userId:user.id},happenedAt:{gte:previousMonth,lt:monthAgo}}}),db.contactRelationTag.groupBy({by:["tag"],where:{contact:{userId:user.id}},_count:{tag:true},orderBy:{_count:{tag:"desc"}},take:8}),db.interaction.groupBy({by:["type"],where:{contact:{userId:user.id},happenedAt:{gte:monthAgo}},_count:{type:true},orderBy:{_count:{type:"desc"}}})]);
  const max=Math.max(...tags.map(tag=>tag._count.tag),1);return <Shell><div className="mx-auto max-w-5xl"><header className="mb-8"><p className="mb-2 text-sm text-muted-foreground">Tendances utiles, sans classement social</p><h1 className="text-3xl font-semibold tracking-tight">Statistiques relationnelles</h1></header><div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat icon={<UsersRound/>} value={contacts} label="personnes dans le carnet"/><Stat icon={<MessageCircle/>} value={recent} label="échanges sur 30 jours"/><Stat icon={<Activity/>} value={`${recent-previous>=0?"+":""}${recent-previous}`} label="évolution vs mois précédent"/></div><div className="grid gap-6 lg:grid-cols-2"><section className="card p-6"><div className="mb-5 flex items-center gap-2"><Tags className="size-4"/><h2 className="font-semibold">Relations les plus présentes</h2></div><div className="space-y-4">{tags.map(item=><Link href={`/contacts?relation=${encodeURIComponent(item.tag)}`} key={item.tag} className="block"><div className="mb-1 flex justify-between text-sm"><span>{item.tag}</span><span className="text-muted-foreground">{item._count.tag}</span></div><div className="progress"><span style={{width:`${item._count.tag/max*100}%`}}/></div></Link>)}{!tags.length&&<Empty/>}</div></section><section className="card p-6"><h2 className="mb-5 font-semibold">Types d’échanges ce mois-ci</h2><div className="space-y-3">{types.map(item=><div key={item.type} className="flex justify-between rounded-lg bg-muted/60 p-3 text-sm"><span>{labels[item.type]||item.type}</span><b>{item._count.type}</b></div>)}{!types.length&&<Empty/>}</div></section></div></div></Shell>;
}
const labels:Record<string,string>={message:"Messages",call:"Appels",meeting:"Rencontres",email:"E-mails"};
function Stat({icon,value,label}:{icon:React.ReactNode;value:string|number;label:string}){return <div className="card p-5"><span className="mb-4 grid size-9 place-items-center rounded-lg bg-muted [&_svg]:size-4">{icon}</span><p className="text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>}
function Empty(){return <p className="text-sm text-muted-foreground">Pas encore assez de données.</p>}
